spec:
  template:
    spec:
      hostNetwork: false
      dnsPolicy: ClusterFirst
      containers:
      - name: metrics-server
        args:
        - --cert-dir=/tmp
        - --secure-port=4443
        - --kubelet-insecure-tls
        - --kubelet-preferred-address-types=InternalIP,Hostname
        readinessProbe:
          httpGet:
            scheme: HTTPS
            path: /readyz
            port: 4443
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        livenessProbe:
          httpGet:
            scheme: HTTPS
            path: /livez
            port: 4443
          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 6
        env:
        - { name: HTTP_PROXY,  value: "" }
        - { name: HTTPS_PROXY, value: "" }
        - { name: NO_PROXY,    value: "127.0.0.1,localhost,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,.svc,.cluster.local" }
