services:
  ids_api:
    image: ids-unsw-api:cpu
    container_name: ids_api
    build:
      context: ../..          # project root (where Dockerfile.api is)
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      IDS_API_TOKEN: "supersecret123"
      MLFLOW_TRACKING_URI: "http://host.docker.internal:5000"
    volumes:
      - type: bind
        source: "/mnt/c/Users/vince/Coursework/Housing Project/mlflow"
        target: /mlflow
        read_only: true

  ids_ui:
    image: ids-dash-ui
    container_name: ids_ui
    build:
      context: .
      dockerfile: Dockerfile.ui
    ports:
      - "8050:8050"
    environment:
      IDS_API_URL: "http://ids_api:8000"
      IDS_API_TOKEN: "supersecret123"
    depends_on:
      - ids_api
