apiVersion: apps/v1
kind: Deployment
metadata:
  name: ids-api
spec:
  template:
    spec:
      containers:
      - name: api
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
