apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
spec:
  template:
    spec:
      containers:
      - name: ui
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 512Mi
