name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  mlflow:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install mlflow onnx
      - name: MLflow smoke run (log bundle)
        run: |
          python - <<'PY'
          import pathlib, mlflow
          mlflow.set_tracking_uri("file:./mlruns")
          mlflow.set_experiment("ci-smoke")
          b = pathlib.Path("notebooks/ids_unsw/models/bundle_xgb")
          assert (b/"xgb.onnx").exists()
          with mlflow.start_run(run_name="ci_smoke") as run:
              mlflow.log_artifact(b/"xgb.onnx", artifact_path="xgb")
              mlflow.log_artifact(b/"feature_names.json", artifact_path="xgb")
              mlflow.log_artifact(b/"metadata.json", artifact_path="xgb")
              print("RUN_ID:", run.info.run_id)
          PY
      - name: Upload MLflow artifact store
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns

  docker:
    runs-on: ubuntu-latest
    needs: [test, mlflow]
    steps:
      - name: Checkout (with LFS for ONNX bundle)
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build a local image and smoke-test it before pushing
      - name: Build local image for smoke test
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          load: true          # produces a local image
          tags: localtest:ci

      - name: Smoke test container
        run: |
          docker run -d --rm --name idsapi -p 8000:8000 \
            -e IDS_API_TOKEN=supersecret123 \
            localtest:ci
          sleep 5
          curl -sSf -H "Authorization: Bearer supersecret123" http://localhost:8000/health
          docker stop idsapi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Compute tags/labels
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/ids-unsw-api
          tags: |
            type=raw,value=latest
            type=raw,value=sha-${{ github.sha }}

      - name: Build & push release image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

