name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            pip install onnxruntime==1.18.* onnx==1.16.* numpy pandas mlflow==3.3.2 pytest
          fi

      - name: Run tests
        run: pytest -q

      - name: MLflow smoke run (creates ./mlruns)
        run: |
          python - <<'PY'
          import os, mlflow
          mlflow.set_tracking_uri("file://" + os.path.abspath("mlruns"))
          mlflow.set_experiment("ci-smoke")
          with mlflow.start_run(run_name="ci"):
              mlflow.log_metric("ok", 1.0)
          print("mlflow smoke run completed")
          PY

      - name: Upload mlruns artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns
