# .github/workflows/ci.yml
name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  mlflow:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: python -m pip install --upgrade pip
      - run: pip install mlflow onnx
      - name: MLflow smoke run (log bundle)
        run: |
          python - <<'PY'
          import pathlib, mlflow
          mlflow.set_tracking_uri("file:./mlruns")
          mlflow.set_experiment("ci-smoke")
          b = pathlib.Path("notebooks/ids_unsw/models/bundle_xgb")
          assert (b/"xgb.onnx").exists()
          with mlflow.start_run(run_name="ci_smoke") as run:
              mlflow.log_artifact(b/"xgb.onnx", artifact_path="xgb")
              mlflow.log_artifact(b/"feature_names.json", artifact_path="xgb")
              mlflow.log_artifact(b/"metadata.json", artifact_path="xgb")
              print("RUN_ID:", run.info.run_id)
          PY
      - name: Upload MLflow artifact store
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns
