name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests
        run: pytest -q

      - name: MLflow smoke: log tiny run
        run: |
          python - <<'PY'
          import mlflow, pathlib
          mlflow.set_tracking_uri("file:mlruns")   # local file store
          mlflow.set_experiment("ci-smoke")
          with mlflow.start_run(run_name="gha"):
              mlflow.log_param("ci", "true")
              mlflow.log_metric("auc_stub", 0.5)
              # prove artifact logging works (use a small file from the repo)
              mlflow.log_artifact(
                  "notebooks/ids_unsw/models/bundle_xgb/metadata.json",
                  artifact_path="xgb"
              )
          print("Done; mlruns exists:", pathlib.Path("mlruns").exists())
          PY

      - name: Upload mlruns artifact
        uses: actions/upload-artifact@v4
        with:
          name: mlruns
          path: mlruns
          if-no-files-found: error
